name: Build Linux

on:
  push:
    branches: [ master, gtk3, fullvcpkg ]
  pull_request:
    branches: [ master, gtk3, fullvcpkg ]
  release:
    types: [published]

jobs:
  build:
    name: "Build: ${{ matrix.arch }} ${{ matrix.os }} - ${{ matrix.gtkver }} - ${{ matrix.upload_suffix }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        arch: [x64]
        config: [Release]
        gtkver: [GTK2, GTK3]
        statictype: [ON, OFF]
        include:
          - statictype: ON
            preset_suffix: ""
            upload_suffix: static
          - statictype: OFF
            preset_suffix: "-Dynamic"
            upload_suffix: shared

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          set -e
          sudo apt install -y libgtk2.0-dev libgtk-3-dev libudev-dev autoconf automake libtool pkg-config libxi-dev libxtst-dev libx11-dev libgles2-mesa-dev intltool

      - name: Generate tilp+gfm i18n resources
        run: |
          cd  gfm/trunk/po; intltool-update --pot; intltool-update fr; cd ../../..
          cd tilp/trunk/po; intltool-update --pot; intltool-update fr; intltool-update de; cd ../../..

      - name: workaround for default apt mirror connectivity issues
        run: |
          sudo sed -i 's/azure\.//' /etc/apt/sources.list

      - name: Install latest CMake
        uses: lukka/get-cmake@a70f1cfa1857a3eecfe0d34962269e1b1e8be56c # latest as of 2024-08-08

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@d87e7fac99f22776a4973d7e413921ea254c1fc9 # latest as of 2024-08-08

      - name: create install folder
        run: |
          mkdir -p "${{ github.workspace }}/tilp.build/Linux-${{ matrix.arch }}-${{ matrix.gtkver }}/prefix"

      - name: Build and install tilp (${{ matrix.gtkver }}) and gfm ${{ matrix.config }} on Linux ${{ matrix.arch }}
        uses: lukka/run-cmake@4b1adc1944be8367be9f4e08303ce49918db8e3c # latest as of 2024-08-08
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'Linux-${{ matrix.arch }}-${{ matrix.gtkver }}${{ matrix.preset_suffix }}'
          configurePresetAdditionalArgs: "['-DDEPS_RELEASE_ONLY=ON']"
          buildPreset: 'Linux-${{ matrix.arch }}-${{ matrix.gtkver }}${{ matrix.preset_suffix }}-${{ matrix.config }}'
          buildPresetAdditionalArgs: "['--target', 'install']"
        env:
          CMAKE_INSTALL_PREFIX_OVERRIDE: ${{ github.workspace }}/tilp.build/Linux-${{ matrix.arch }}-${{ matrix.gtkver }}/prefix
          VCPKG_DEFAULT_HOST_TRIPLET: ${{ matrix.arch }}-linux-release
          VCPKG_FORCE_SYSTEM_BINARIES: 1

      - name: Upload install folder
        uses: actions/upload-artifact@v4
        with:
          name: tilp_and_gfm_${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.gtkver }}_${{ matrix.upload_suffix }}Deps
          path: ${{ github.workspace }}/tilp.build/Linux-${{ matrix.arch }}-${{ matrix.gtkver }}/prefix
